-- MySQL Script generated by MySQL Workbench
-- Fri Mar 25 14:35:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen2Parcial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen2Parcial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen2Parcial` DEFAULT CHARACTER SET utf8 ;
USE `Examen2Parcial` ;

-- -----------------------------------------------------
-- Table `Examen2Parcial`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`usuario` (
  `Codigo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(15) NULL,
  `EstaActivo` TINYINT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2Parcial`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`producto` (
  `Codigo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2Parcial`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`pedido` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdentidadCliente` VARCHAR(20) NULL,
  `Cliente` VARCHAR(45) NULL,
  `Fecha` TIMESTAMP NULL,
  `Subtotal` DECIMAL NULL,
  `Impuesto` DECIMAL NULL,
  `Total` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen2Parcial`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen2Parcial`.`DetallePedido` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `CodigoProducto` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  `Precio` DECIMAL NULL,
  `Total` DECIMAL NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_detallepedido_pedido_idx` (`IdPedido` ASC) VISIBLE,
  INDEX `fk_detallepedido_producto_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_detallepedido_pedido`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `Examen2Parcial`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallepedido_producto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `Examen2Parcial`.`producto` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
